"""empty message

Revision ID: 09656917d4d5
Revises: d49930da8058
Create Date: 2018-03-02 14:36:51.641967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09656917d4d5'
down_revision = 'd49930da8058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('subtitle', sa.String(length=40), nullable=True),
    sa.Column('body', sa.String(length=280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
